kclars/config/routes.rb
Kclars::Application.routes.draw do
 
  get "sessions/new"

  resources :users

  resources :departments

  resources :logins

  resources :votes

  resources :sessions, :only => [ :new, :create, :destroy]
  resources :students

  get "stdregister/index"

  get "invindex/index"

  get "invindex/show"

    

  
  resources :groups
  resources :events

  get "pages/home"
  match '/invindex' => 'groups#invindex'
  get "groups/new"
  match '/getid/:id' => 'groups#getid'  
  root :to => 'pages#home'
  match '/recommendations' => 'students#recr'
  match '/register', :to => 'users#new'    
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/invindex/:id', :to => 'invindex#show'
  match '/getContentRecommendations/:id', :to => 'students#getContentRecommendations'
  match '/getContentRecommendations' => 'students#getContentRecommendations'
   
  

end

kclars/app/models/user.rb
#
# Much of the code in this section was taken
# from Michael Hartl's Book Ruby on Rails: Tutorials
#ruby.railstutorial.org

require 'digest'
class User < ActiveRecord::Base
 attr_accessor :password
 attr_accessible :name, :email, :password, :password_confirmation

 email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 
 validates :name, :presence => true,
  		  :length => { :maximum => 50 }
 validates :email, :presence => true,
    		   :format => { :with => email_regex },
  		   :uniqueness => { :case_sensitive => false }
 
 validates :password, :presence => true,
  		     :confirmation => true,
  		     :length => { :within => 6..40 }
  
 before_save :encrypt_password

 def has_password?(submitted_password)
   encrypted_password == encrypt(submitted_password)  
 end

 def self.authenticate(email, submitted_password)
  user = find_by_email(email)
  return nil if user.nil?
  return user if user.has_password?(submitted_password)
 end
  
 def self.authenticate_with_salt(id, cookie_salt)
   user = find_by_id(id)
   (user && user.salt == cookie_salt) ? user : nil
 end

 private
  def encrypt_password
    self.salt = make_salt unless has_password?(password)
   self.encrypted_password = encrypt(password)
  end
  def encrypt(string)
   secure_hash("#{salt}--#{string}")
   #string
  end
  def make_salt
   secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
   Digest::SHA2.hexdigest(string)
  end
  




end

kclars/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [ :edit, :update ]
  before_filter :correct_user, :only => [ :edit, :update ]
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])
    @title = @user.name
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    @title = "Sign Up"
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        sign_in @user
        flash[:success] = "welcome to the sample app!"
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        @title = "sign up"
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
 private
   def authenticate 
     deny_access unless signed_in?
   end
   def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
   end
end

kclars/app/helpers/users_helper.rb
module UsersHelper
end

kclars/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

kclars/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

kclars/app/views/users/index.html.erb
<div class="users_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<p>
<% form_tag groups_path, :method => 'get' do %>
<p> 
 <%= text_field_tag :search, params[:search]  %>
 <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
</p>
</div>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Password confirmation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.password_confirmation %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

kclars/app/views/users/new.html.erb
<h1>New user</h1>



<%= render 'form' %>

<%= link_to 'Back', users_path %>

kclars/app/views/users/show.html.erb
<div class="users_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<p>
<% form_tag groups_path, :method => 'get' do %>
<p> 
 <%= text_field_tag :search, params[:search]  %>
 <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
</p>
</div>
<p id="notice"><%= notice %></p>
<h1> <%= @user.name %>

<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
      
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Password confirmation:</b>
  <%= @user.password_confirmation %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>