kclars/config/routes.rb
Kclars::Application.routes.draw do
 
  get "sessions/new"

  resources :users

  resources :departments

  resources :logins

  resources :votes

  resources :sessions, :only => [ :new, :create, :destroy]
  resources :students

  get "stdregister/index"

  get "invindex/index"

  get "invindex/show"

    

  
  resources :groups
  resources :events

  get "pages/home"
  match '/invindex' => 'groups#invindex'
  get "groups/new"
  match '/getid/:id' => 'groups#getid'  
  root :to => 'pages#home'
  match '/recommendations' => 'students#recr'
  match '/register', :to => 'users#new'    
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/invindex/:id', :to => 'invindex#show'
  match '/getContentRecommendations/:id', :to => 'students#getContentRecommendations'
  match '/getContentRecommendations' => 'students#getContentRecommendations'
   
  

end

kclars/app/models/login.rb
class Login < ActiveRecord::Base
 
 validate :authenticate
 
 def authenticate(username, password)
   user = Student.find_by_username(username) 
   if user.nil? | user.blank? | user.password != password 
    error.add(:username, "username does not exist or password does not match!") 
   end
 end
   
   

end

kclars/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  # GET /logins
  # GET /logins.xml
  def index
    @logins = Login.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @logins }
    end
  end

  # GET /logins/1
  # GET /logins/1.xml
  def show
    @login = Login.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @login }
    end
  end

  # GET /logins/new
  # GET /logins/new.xml
  def new
    @login = Login.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @login }
    end
  end

  # GET /logins/1/edit
  def edit
    @login = Login.find(params[:id])
  end

  # POST /logins
  # POST /logins.xml
  def create
    @login = Login.new(params[:login])

    respond_to do |format|
      if @login.save
        format.html { redirect_to(@login, :notice => 'Login was successfully created.') }
        format.xml  { render :xml => @login, :status => :created, :location => @login }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @login.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /logins/1
  # PUT /logins/1.xml
  def update
    @login = Login.find(params[:id])

    respond_to do |format|
      if @login.update_attributes(params[:login])
        format.html { redirect_to(@login, :notice => 'Login was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @login.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.xml
  def destroy
    @login = Login.find(params[:id])
    @login.destroy

    respond_to do |format|
      format.html { redirect_to(logins_url) }
      format.xml  { head :ok }
    end
  end
end

kclars/app/helpers/logins_helper.rb
module LoginsHelper
end

kclars/app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

kclars/app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

kclars/app/views/logins/index.html.erb
<h1>Listing logins</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logins.each do |login| %>
  <tr>
    <td><%= login.username %></td>
    <td><%= login.password %></td>
    <td><%= link_to 'Show', login %></td>
    <td><%= link_to 'Edit', edit_login_path(login) %></td>
    <td><%= link_to 'Destroy', login, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Login', new_login_path %>

kclars/app/views/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

kclars/app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @login.username %>
</p>

<p>
  <b>Password:</b>
  <%= @login.password %>
</p>


<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>