kclars/config/routes.rb
Kclars::Application.routes.draw do
 
  get "sessions/new"

  resources :users

  resources :departments

  resources :logins

  resources :votes

  resources :sessions, :only => [ :new, :create, :destroy]
  resources :students

  get "stdregister/index"

  get "invindex/index"

  get "invindex/show"

    

  
  resources :groups
  resources :events

  get "pages/home"
  match '/invindex' => 'groups#invindex'
  get "groups/new"
  match '/getid/:id' => 'groups#getid'  
  root :to => 'pages#home'
  match '/recommendations' => 'students#recr'
  match '/register', :to => 'users#new'    
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/invindex/:id', :to => 'invindex#show'
  match '/getContentRecommendations/:id', :to => 'students#getContentRecommendations'
  match '/getContentRecommendations' => 'students#getContentRecommendations'
   
  

end

kclars/app/models/department.rb
class Department < ActiveRecord::Base
end

kclars/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # GET /departments
  # GET /departments.xml
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @departments }
      format.json {render :json => @departments }
    end
  end

  # GET /departments/1
  # GET /departments/1.xml
  def show
    @department = Department.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/new
  # GET /departments/new.xml
  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @department }
    end
  end

  # GET /departments/1/edit
  def edit
    @department = Department.find(params[:id])
  end

  # POST /departments
  # POST /departments.xml
  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to(@department, :notice => 'Department was successfully created.') }
        format.xml  { render :xml => @department, :status => :created, :location => @department }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /departments/1
  # PUT /departments/1.xml
  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to(@department, :notice => 'Department was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @department.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.xml
  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to(departments_url) }
      format.xml  { head :ok }
    end
  end
end

kclars/app/helpers/departments_helper.rb
module DepartmentsHelper
end

kclars/app/views/departments/_form.html.erb
<%= form_for(@department) do |f| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% @department.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :ndate %><br />
    <%= f.date_select :ndate %>
  </div>
  <div class="field">
    <%= f.label :ntime %><br />
    <%= f.time_select :ntime %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

kclars/app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render 'form' %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

kclars/app/views/departments/index.html.erb
<div class="departments_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<p>
<% form_tag groups_path, :method => 'get' do %>
<p>
 <%= text_field_tag :search, params[:search]  %>
 <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
</p>

</div>


<table>
  <tr>
    <th>Title</th>
    <th>Date</th>
    <th>Time</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departments.each do |department| %>
  <tr>
    <td><%= department.title %></td>
    <td><%= department.ndate %></td>
    <td><%= department.ntime %></td>
    <td><%= department.description %></td>
    <td><%= link_to 'Show', department %></td>
    <td><%= link_to 'Edit', edit_department_path(department) %></td>
    <td><%= link_to 'Destroy', department, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add News/Events', new_department_path %>

kclars/app/views/departments/new.html.erb
<h2>Add News/Events</h2>
<div class="departments_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<p>
</p>

</div>

<%= render 'form' %>

<%= link_to 'Back', departments_path %>

kclars/app/views/departments/show.html.erb
<div class="departments_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<p>
</p>

</div>

<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @department.title %>
</p>

<p>
  <b>Date:</b>
  <%= @department.ndate %>
</p>

<p>
  <b>Time:</b>
  <%= "#{@department.ntime.hour}:#{@department.ntime.min}" %>
</p>

<p>
  <b>Description:</b>
  <%= @department.description %>
</p>


<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>