kclars/config/routes.rb
Kclars::Application.routes.draw do
 
  get "sessions/new"

  resources :users

  resources :departments

  resources :logins

  resources :votes

  resources :sessions, :only => [ :new, :create, :destroy]
  resources :students

  get "stdregister/index"

  get "invindex/index"

  get "invindex/show"

    

  
  resources :groups
  resources :events

  get "pages/home"
  match '/invindex' => 'groups#invindex'
  get "groups/new"
  match '/getid/:id' => 'groups#getid'  
  root :to => 'pages#home'
  match '/recommendations' => 'students#recr'
  match '/register', :to => 'users#new'    
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/invindex/:id', :to => 'invindex#show'
  match '/getContentRecommendations/:id', :to => 'students#getContentRecommendations'
  match '/getContentRecommendations' => 'students#getContentRecommendations'
   
  

end

kclars/app/models/student.rb
class Student < ActiveRecord::Base
 serialize :queryvector 
 validates :name, :username, :email, :presence => true
 validates :username, :email, :uniqueness => true, :on => :create

 email_regex = /^[a-zA-Z]+[.]([a-zA-Z]+[-_]*[a-zA-Z]+)*@kcl.ac.uk$/
 validates :email, :format => { :with => email_regex } 
 #validate :check_id
 has_many :votes, :dependent => :destroy
 has_many :events, :through => :votes, :source => "event_id"

 before_save :remove_stop_words
 
 #private 
 
 #def  check_id
 #  if Stdregister.find_by_stdid(self.stdid).blank? 
 #    errors.add(:stdid, "student id does not exist in INF dept")
 # 
 #  end
 #end

  
   def remove_stop_words
    if self.bhistory != nil
     string = self.bhistory
     stop_words = %w{a about above after again against all am an and any are aren't as at be because been before being below between both but by can't cannot could couldn't \
     did didn't do does doesn't doing don't down during each few for from further had hadn't has hasn't have haven't having he he'd himself his how how's i i'd i'll i'm i've if in into \
     is isn't it it's its itself let's me more most mustn't my myself no nor not of off on once only or other ought our ours ourselves out over own same shan't she she'd she'll she's should \
     shouldn't so some such than that that's hte their hteirs them themselves then there there's these they they'd they'll they're they've this those through to too under until up very was wasn't \
     we we'd we'll we're we've were weren't what what's when when's where where's which while who who's whom why why's with won't would wouldn't you you'd you'll you're you've your yours \
     yourself yourselves php html js cgi login owa index auth srf ppsecur redirect htm}
     
     words = string.scan(/\w+/)
     key_words = words.select { |word| !stop_words.include?(word) }
     self.bhistory = key_words.join(' ')
     build_query_vector(self.bhistory)       
    end
   end
   
   def build_query_vector(string)
     hash = Hash.new(0)
     words = string.downcase.scan(/[\w']+/) 
     for w in words
      hash[w] += 1
     end
     etf = euclideanNormalizedScore(hash)
     self.queryvector = etf
     self.queryvector = Hash[queryvector.to_a.shuffle[0..10]]

   end  
  
   def euclideanNormalizedScore(t)
    sum = 0
    t.each { |k, v| sum += v ** 2}
    t.each { |k, v| p = t[k].to_f / sum; s = p.round(3); t[k] = s }
    return t
   end
 

  
 









end

kclars/app/controllers/students_controller.rb
require './lib/recommendations.rb'
require '././recommend.rb'
class StudentsController < ApplicationController
  # GET /students
  # GET /students.xml
  def index
   @students = Student.where("").order('id').page(params[:page]).per(10)
   #@students = Student.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @students }
    end
  end

  # GET /students/1
  # GET /students/1.xml
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/new
  # GET /students/new.xml
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.xml
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to(@student, :notice => 'Student was successfully created.') }
        format.xml  { render :xml => @student, :status => :created, :location => @student }
        UserMailer.deliver_registration_confirmation(@student) 
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.xml
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(@student, :notice => 'Student was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.xml
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to(students_url) }
      format.xml  { head :ok }
    end
  end
  
  def recr 
    @b = "."
    @array = []
    r = Recommendations.new
    app = App.new
    @h = Hash.new(0)
    @final = Hash.new(0)
    @s = Student.all
    @s.each do |x|
     v = x.votes  
     hash = Hash.new 
     v.each do |p|
      
      hash[p.event_id] = p.vote
      
     end   
     @final[x.name] = hash
    end
   
     @b = r.getRecommendations(@final,"Chirag")
    
  end
  
  def getContentRecommendations
   @student = Student.find(params[:id])
   f = Fatos.new
   @results = f.second(f.first(@student))   
   respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @results }
    end

  end
   
end

kclars/app/helpers/students_helper.rb
module StudentsHelper
end

kclars/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :stdid %><br />
    <%= f.text_field :stdid %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :bhistory %><br />
    <%= f.text_area :bhistory %>
  </div>
  <div class="field">
    <%= f.label :rsvps %><br />
    <%= f.text_area :rsvps %>
  </div>
  <div class="field">
    <%= f.label :tutor %><br />
    <%= f.text_field :tutor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

kclars/app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

kclars/app/views/students/delete.html.erb
<h1>Students#delete</h1>
<p>Find me in app/views/students/delete.html.erb</p>

kclars/app/views/students/edit.html.erb
<div class="group_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<p>
<% form_tag groups_path, :method => 'get' do %>
<p> 
 <%= text_field_tag :search, params[:search]  %>
 <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
</p>
</div>
<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

kclars/app/views/students/getContentRecommendations.html.erb
<%=  @results %>
<br />
<br />
<br />

kclars/app/views/students/index.html.erb
<div class="group_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<p>
<% form_tag groups_path, :method => 'get' do %>
<p> 
 <%= text_field_tag :search, params[:search]  %>
 <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
</p>
</div>
<table>
  <tr>
    <th>Name</th>
    <th>Stdid</th>
    <th>Email</th>
    <th>Browser History</th>
    <th>Query Vector</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.name %></td>
    <td><%= student.stdid %></td>
    <td><%= student.email %></td>
    <td><%= student.bhistory %></td>
    <td><%= student.queryvector %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<%= paginate @students %>
<br />

<%= link_to 'New Student', new_student_path %>

kclars/app/views/students/new.html.erb
<div class="group_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<h3>New Student</h3>
<p>
<% form_tag groups_path, :method => 'get' do %>
<p> 
 <%= text_field_tag :search, params[:search]  %>
 <%= submit_tag "Search", :name => nil %>
</p>
<% end %>
</p>

</div>
<%= render 'form' %>

<%= link_to 'Back', students_path %>

kclars/app/views/students/recr.html.erb
<%= debug @final %>
<%= @b %>

kclars/app/views/students/show.html.erb
<div class="group_table" style="margin-left:16.5%">
<div id="navigation" style="background:white;border:1px outset cadetblue;">
<p>

</div>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Stdid:</b>
  <%= @student.stdid %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>

<p>
  <b>Modules:</b>
  <%= @student.modules %>
</p>

<p>
  <b>Rsvps:</b>
  <%= @student.rsvps %>
</p>

<p>
  <b>Tutor:</b>
  <%= @student.tutor %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

kclars/app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>